### ISSUE TITLE
Right to left support 

### ISSUE THREAD

**Issue by mohsen1** [rgbkrk/covfefe#10]
I wrote a library to detect string direction:

https://www.npmjs.com/package/string-direction

I'm on my phone otherwise would've made a pull request.

**Comment by BinaryMuse** [comment]
is this a political pun

**Comment by rgbkrk** [comment]
`/me groans`

Ok, _now_ I get it.

**Comment by BLamy** [comment]
@rgbkrk I've needed this bug fixed for over 7 hours now what's the hold up covfefe.

**Comment by rgbkrk** [comment]
I've needed this bug fixed for months now.

**Comment by mohsen1** [comment]
Your testing framework don't like RTL and Bidi strings.
