### ISSUE TITLE
Link to tweet is dead

### ISSUE THREAD

**Issue by KoryNunn** [rgbkrk/covfefe#14]
We need to find a replacement, like a screenshot or something.

**Comment by dufferzafar** [comment]
YES! Came late to this party (from HN.) Have no idea what this repo is about. :/

**Comment by daviddarnes** [comment]
https://twitter.com/gray/status/869858875373170688
![dbjccbqxyaalgdm](https://cloud.githubusercontent.com/assets/1177460/26636606/3a8379f2-4615-11e7-8e81-b30d1fcb523d.jpg)

**Comment by rgbkrk** [comment]
Screenshot would be good. #15 added an archived link.
