### ISSUE TITLE
Can you add a license so I can contribute :D

### ISSUE THREAD

**Issue by MylesBorins** [rgbkrk/covfefe#4]

**Comment by rgbkrk** [comment]
Oh snap, it's in the package.json but there is no license file.

Despite the field covfefe

**Comment by rgbkrk** [comment]
Done

covfefe

**Comment by MylesBorins** [comment]
you better not have done the covfefe license

**Comment by junosuarez** [comment]
its bsd3clause covfefe

**Comment by rgbkrk** [comment]
I'm in Berkeley right now, it's geopolitically based covfefe
